// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: AClock

#ifndef _ACLOCK_UI_H
#define _ACLOCK_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

void menuUpAnim_Animation(lv_obj_t * TargetObject, int delay);
void menuDownAnim_Animation(lv_obj_t * TargetObject, int delay);
void showSideMenu_Animation(lv_obj_t * TargetObject, int delay);
void menuReachTop_Animation(lv_obj_t * TargetObject, int delay);
void menuReachBottom_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_dormancyScreen
void ui_dormancyScreen_screen_init(void);
void ui_event_dormancyScreen(lv_event_t * e);
extern lv_obj_t * ui_dormancyScreen;
extern lv_obj_t * ui_timeLabel;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_sideMenu;
extern lv_obj_t * ui_menuHighlight;
extern lv_obj_t * ui_menuContent;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Panel5;
// SCREEN: ui_clockScreen
void ui_clockScreen_screen_init(void);
extern lv_obj_t * ui_clockScreen;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Arc1;
// SCREEN: ui_weatherScreen
void ui_weatherScreen_screen_init(void);
extern lv_obj_t * ui_weatherScreen;
// SCREEN: ui_airQualityScreen
void ui_airQualityScreen_screen_init(void);
extern lv_obj_t * ui_airQualityScreen;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_sensor_png);    // assets/Sensor.png
LV_IMG_DECLARE(ui_img_clock_png);    // assets/Clock.png
LV_IMG_DECLARE(ui_img_1407854121);    // assets/cloud-sun.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
