// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: AClock

#include "ui.h"

void ui_airQualityScreen_screen_init(void)
{
    ui_airQualityScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_airQualityScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_airQualityScreen, lv_color_hex(0x065370), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_airQualityScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


}
