// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: AClock

#include "ui.h"

void ui_clockScreen_screen_init(void)
{
    ui_clockScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_clockScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_clockScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clockScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeLabel2 = lv_label_create(ui_clockScreen);
    lv_obj_set_width(ui_timeLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_timeLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timeLabel2, "13:42");
    lv_obj_set_style_text_color(ui_timeLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timeLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timeLabel2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeSecArc = lv_arc_create(ui_clockScreen);
    lv_obj_set_width(ui_timeSecArc, 180);
    lv_obj_set_height(ui_timeSecArc, 180);
    lv_obj_set_align(ui_timeSecArc, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_timeSecArc, 0, 360);
    lv_arc_set_value(ui_timeSecArc, 0);
    lv_arc_set_bg_angles(ui_timeSecArc, -90, 270);
    lv_obj_set_style_bg_color(ui_timeSecArc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_timeSecArc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_timeSecArc, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_timeSecArc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_timeSecArc, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_timeSecArc, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_timeSecArc, lv_color_hex(0xFF2C00), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_timeSecArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

}
